(function(g){var window=this;'use strict';var My=function(h){h.publish("cardstatechange",h.ud()&&h.Q7()?1:0)},FB=function(h,W){var c=g.sI(W),V=c?W:arguments;
for(c=c?0:1;c<V.length;c++){if(h==null)return;h=h[V[c]]}return h},VFU=function(h){var W=g.wb(h);
h=g.WW(h);return new g.ts(W.x,W.y,h.width,h.height)},$Tt=function(h,W,c){var V=V===void 0?{}:V;
var H;return H=g.qz(h,W,function(){g.xk(H);c.apply(h,arguments)},V)},ft=function(h){h=g.EI(h);
delete yS[h];g.GF(yS)&&P$&&P$.stop()},HZ6=function(){P$||(P$=new g.oD(function(){sKS()},20));
var h=P$;h.isActive()||h.start()},sKS=function(){var h=g.Gt();
g.k6(yS,function(W){B_f(W,h)});
g.GF(yS)||HZ6()},bE=function(h,W,c,V){g.sb.call(this);
if(!Array.isArray(h)||!Array.isArray(W))throw Error("Start and end parameters must be arrays");if(h.length!=W.length)throw Error("Start and end points must be the same length");this.W=h;this.S=W;this.duration=c;this.C=V;this.coords=[];this.progress=this.N=0;this.Y=null},B_f=function(h,W){W<h.startTime&&(h.endTime=W+h.endTime-h.startTime,h.startTime=W);
h.progress=(W-h.startTime)/(h.endTime-h.startTime);h.progress>1&&(h.progress=1);h.N=1E3/(W-h.Y);h.Y=W;E3$(h,h.progress);h.progress==1?(h.X=0,ft(h),h.onFinish(),h.J7()):h.isPlaying()&&h.U9()},E3$=function(h,W){typeof h.C==="function"&&(W=h.C(W));
h.coords=Array(h.W.length);for(var c=0;c<h.W.length;c++)h.coords[c]=(h.S[c]-h.W[c])*W+h.W[c]},RYI=function(h,W){g.mm.call(this,h);
this.coords=W.coords;this.x=W.coords[0];this.y=W.coords[1];this.z=W.coords[2];this.duration=W.duration;this.progress=W.progress;this.fps=W.N;this.state=W.X},TD=function(h,W,c,V,H){bE.call(this,W,c,V,H);
this.element=h},JIt=function(h,W,c,V,H){if(W.length!=2||c.length!=2)throw Error("Start and end points must be 2D");
TD.call(this,h,W,c,V,H)},uxf=function(h){return Math.pow(h,3)},dTK=function(h){return 3*h*h-2*h*h*h},GmU=function(h){g.N.call(this);
this.W=h||window;this.X=[]},Ny=function(h){return h.baseUrl||null},XB=function(h,W){return g.Lf(g.xw(h,W),function(c){return!!c})},ZZX=function(h,W,c){function V(qL){var Rk=qL.hovercardButton;
if(!Rk)return null;Rk=Rk.subscribeButtonRenderer;if(!Rk)return null;var JN=B(Rk.unsubscribedButtonText),Wd=B(Rk.subscribedButtonText);if(Rk.subscribed){var Uv=B(Rk.subscriberCountWithUnsubscribeText);var gN=B(Rk.subscriberCountText)}else Uv=B(Rk.subscriberCountText),gN=B(Rk.subscriberCountWithSubscribeText);var W2=null;if(qL.signinEndpoint){W2=FB(qL,"signinEndpoint","webNavigationEndpointData","url");if(!W2){var lK,Rf;W2=(Rf=g.v((lK=Rk.signInEndpoint)==null?void 0:lK.commandMetadata,g.i5))==null?
void 0:Rf.url}if(!W2)return null}return JN&&(Wd||W2)?{subscribed:Rk.subscribed,subscribeText:JN,subscribeCount:Uv,unsubscribeText:Wd,unsubscribeCount:gN,enabled:Rk.enabled,signinUrl:W2,classic:qL.useClassicSubscribeButton}:null}
function H(qL){if(qL){var Rk=[],JN=qL.videoId;JN&&Rk.push("v="+JN);(JN=qL.playlistId)&&Rk.push("list="+JN);(qL=qL.startTimeSeconds)&&Rk.push("t="+qL);return"/watch?"+Rk.join("&")}}
function B(qL){if(!qL)return null;var Rk=qL.simpleText;return Rk?Rk:qL.runs?g.xw(qL.runs,function(JN){return JN.text}).join(""):null}
W=W.endscreenElementRenderer;if(!W)return null;var E=W.style,J=W.endpoint||{},u=null,d=null,G=!1,Z=null,r=null,q=null,x=null,z=!1,L=null,M=null,U=null,y=null,T=null,m=null;if(E==="VIDEO")g.v(J,g.C4)?u=g.v(J,g.C4).url:(m=g.v(J,g.nC),u=H(m)),d=!1,Z=h,W.thumbnailOverlays?(G=W.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=B(G.text),G=G.style==="LIVE"):r=B(W.videoDuration);else if(E==="PLAYLIST")g.v(J,g.C4)?u=g.v(J,g.C4).url:(m=g.v(J,g.nC),u=H(m)),d=!1,Z=h,q=B(W.playlistLength);else if(E===
"CHANNEL"){if(z=FB(J,"browseEndpoint","browseId"))x=z,u="/channel/"+x;d=!1;Z="new";(z=!!W.isSubscribe)?L=V(W):M=B(W.subscribersText)}else E==="WEBSITE"?((U=FB(J,"urlEndpoint","url"))&&(u=U),d=!0,Z="new",U=W.icon.thumbnails[0].url):E==="CREATOR_MERCHANDISE"&&(W.productPrice&&(y=B(W.productPrice)),W.additionalFeesText&&(T=B(W.additionalFeesText)),(d=FB(J,"urlEndpoint","url"))&&(u=d),d=!0,Z="new");h=FB(W,"title","accessibility","accessibilityData","label");var D=W.endpoint?W.endpoint.clickTrackingParams:
null,O="";if(W.metadata){var Bd=B(W.metadata);Bd&&(O=Bd)}return{id:"element-"+c,type:E,title:B(W.title),metadata:O,callToAction:B(W.callToAction),Lh:W.image,iconUrl:U,left:Number(W.left),width:Number(W.width),top:Number(W.top),aspectRatio:Number(W.aspectRatio),startMs:Math.floor(Number(W.startMs)),endMs:Math.floor(Number(W.endMs)),videoDuration:r,Mb:G,playlistLength:q,channelId:x,subscribeButton:L,subscribersText:M,isSubscribe:z,targetUrl:u||null,mM:d,sessionData:D?{itct:D}:null,mYf:Z,Vo:h?h:null,
isPlaceholder:W.isPlaceholder,impressionUrls:XB(W.impressionUrls||[],Ny),YV:XB(W.hovercardShowUrls||[],Ny),clickUrls:XB(J.loggingUrls||[],Ny),visualElement:g.GE(W.trackingParams),productPrice:y,additionalFeesText:T,watchEndpoint:m||null}},rI2=function(h,W){var c={startMs:Math.floor(Number(h.startMs)),
impressionUrls:XB(h.impressionUrls||[],Ny),elements:XB(h.elements||[],function(V,H){return ZZX(W,V,H)})};
h.trackingParams&&(c.visualElement=g.GE(h.trackingParams));return c},qpf=function(h){g.K3.call(this,h);
this.Y=this.endscreen=null;this.W={};this.N={};this.C=this.G=null;this.Z=[];this.X=null;this.XI=!0;this.S=0;h=h.B();this.T=g.Vf(h)||g.sa(h);this.events=new g.lX(this);g.X(this,this.events);this.events.U(this.player,g.mZ("creatorendscreen"),this.onCueRangeEnter);this.events.U(this.player,g.om("creatorendscreen"),this.onCueRangeExit);this.events.U(this.player,"resize",this.I1);this.events.U(window,"focus",this.m$W);this.load();var W=g.Zr("STYLE");(g.sH("HEAD")[0]||document.body).appendChild(W);this.addOnDisposeCallback(function(){g.nk(W)});
W.sheet&&(W.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),W.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},xTX=function(h){return h.player.getVideoData().B0?"current":h.T?"new":"current"},tV=function(h){return h.player.B().playerStyle==="creator-endscreen-editor"},lOc=function(h){var W=h.player.getVideoData(),c=W.videoId;
h.Y&&h.Y.abort();c={method:"POST",onFinish:function(H){var B=h.Y=null;H.status===200&&(H=H.responseText,H.substring(0,3)===")]}"&&(H=H.substring(3),B=JSON.parse(H),B=rI2(B,xTX(h))));v$(h,B)},
urlParams:{v:c},withCredentials:!0};h.T&&(c.urlParams.ptype="embedded");var V=W.Y$;V&&(c.postParams={ad_tracking:V});if(W=g.OYp(W))if(W=g.Eu(W),W=g.$u(W))h.Y=g.nb(W,c)},v$=function(h,W,c){c=c===void 0?!0:c;
h.player.zw("creatorendscreen");h.G&&(h.G.dispose(),h.G=null,h.C.dispose(),h.C=null);for(var V=g.e(Object.values(h.W)),H=V.next();!H.done;H=V.next())H.value.dispose();h.W={};h.N={};h.Z.length>0&&(h.Z.forEach(function(J){J.dispose()}),h.Z.length=0);
h.X&&(g.cD(h.X,"ytp-ce-element-show"),h.X.setAttribute("aria-hidden","true"));h.S=0;if((h.endscreen=W)&&W.elements){c&&n36(h);c=[];V=new g.t$(W.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(V);h.player.B().W||(h.G=new g.p({D:"div",K:"ytp-ce-shadow"}),g.ge(h.player,h.G.element,4),h.C=new g.SL(h.G,200));for(V=0;V<W.elements.length;++V){H=W.elements[V];var B=jK2(h,H);if(B){h.W[H.id]=B;h.N[H.id]=H;g.ge(h.player,B.element,4);var E=new g.t$(H.startMs,H.endMs,{id:"ytp-ce-element-"+
H.id,namespace:"creatorendscreen"});c.push(E);aO2(h,B,H)}else g.Lx(new g.tP("buildEndscreenElement null",H))}h.player.Fi(c);h.I1()}},n36=function(h){var W=g.rc(),c=g.q_();
c&&W&&h.endscreen.visualElement&&g.IW(g.TE)(void 0,c,W,h.endscreen.visualElement)},jK2=function(h,W){var c=null;
switch(W.type){case "VIDEO":h={D:"div",LM:["ytp-ce-element","ytp-ce-video"],J:{tabindex:"0","aria-label":W.Vo||"","aria-hidden":"true"},V:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",J:mi(W)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",J:{href:o6(h,W.targetUrl),tabindex:"-1"},V:[{D:"div",LM:["ytp-ce-video-title","ytp-webkit-ellipsis"],J:{dir:g.Je(W.title||"")},YN:W.title},{D:"div",K:W.Mb?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
YN:W.videoDuration||void 0}]}]};c=new g.p(h);break;case "PLAYLIST":h={D:"div",LM:["ytp-ce-element","ytp-ce-playlist"],J:{tabindex:"0","aria-label":W.Vo||"","aria-hidden":"true"},V:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",J:mi(W)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",J:{href:o6(h,W.targetUrl),tabindex:"-1"},V:[{D:"div",LM:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],J:{dir:g.Je(W.title||"")},YN:W.title},{D:"div",K:"ytp-ce-playlist-count",
V:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",YN:W.playlistLength||void 0}]}]}]};c=new g.p(h);break;case "CHANNEL":c={D:"div",LM:["ytp-ce-element","ytp-ce-channel",W.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],J:{tabindex:"0","aria-label":W.Vo||"","aria-hidden":"true"},V:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",V:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
V:[{D:"div",K:"ytp-ce-expanding-overlay-body",V:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",V:[{D:"a",LM:["ytp-ce-channel-title","ytp-ce-link"],J:{href:o6(h,W.targetUrl),target:"_blank",tabindex:"-1",dir:g.Je(W.title||"")},YN:W.title},W.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",V:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:"",W.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",YN:W.subscribersText}:"",W.metadata?{D:"div",LM:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],YN:W.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",J:mi(W)}]};c=new g.p(c);var V=g.B3(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(W.subscribeButton&&W.channelId){g.he(V,"ytp-ce-subscribe-button");if(h.player.B().W){var H=null;var B=W.sessionData.itct}else H="endscreen",B=null;H=new g.Hm(W.subscribeButton.subscribeText,W.subscribeButton.subscribeCount,W.subscribeButton.unsubscribeText,W.subscribeButton.unsubscribeCount,!!W.subscribeButton.enabled,!!W.subscribeButton.classic,
W.channelId,!!W.subscribeButton.subscribed,H,B,h.player,!1);V.appendChild(H.element);h.Z.push(H)}break;case "WEBSITE":h={D:"div",LM:["ytp-ce-element","ytp-ce-website"],J:{tabindex:"0","aria-label":W.Vo||"","aria-hidden":"true"},V:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",V:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",V:[{D:"div",K:"ytp-ce-expanding-overlay-body",V:[{D:"div",
K:"ytp-ce-expanding-overlay-body-padding",V:[{D:"div",K:"ytp-ce-website-title",J:{dir:g.Je(W.title||"")},YN:W.title},{D:"div",K:"ytp-ce-website-metadata",YN:W.metadata},{D:"a",LM:["ytp-ce-website-goto","ytp-ce-link"],J:{href:o6(h,W.targetUrl),target:"_blank",tabindex:"-1"},YN:W.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",J:mi(W)},{D:"div",K:"ytp-ce-expanding-icon",J:eYu(W.iconUrl)}]};c=new g.p(h);break;case "CREATOR_MERCHANDISE":c="",W.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",
V:[{D:"div",K:"ytp-ce-merchandise-price",YN:W.productPrice}]},W.additionalFeesText&&c.V.push({D:"div",K:"ytp-ce-merchandise-additional-fees",YN:W.additionalFeesText})),h={D:"div",LM:["ytp-ce-element","ytp-ce-merchandise"],J:{tabindex:"0","aria-label":W.Vo||"","aria-hidden":"true"},V:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",V:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
V:[{D:"div",K:"ytp-ce-expanding-overlay-body",V:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",V:[{D:"div",K:"ytp-ce-merchandise-title",J:{dir:g.Je(W.title||"")},YN:W.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",YN:W.metadata},{D:"a",LM:["ytp-ce-merchandise-goto","ytp-ce-link"],J:{href:o6(h,W.targetUrl),target:"_blank",tabindex:"-1"},YN:W.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",J:mi(W)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",V:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",
YN:W.callToAction||void 0}]}]},c=new g.p(h)}W.isPlaceholder&&g.he(c.element,"ytp-ce-placeholder");return c},mi=function(h){if(h.Lh)var W=h.Lh.thumbnails;
return eYu(W?W[W.length-1].url:null)},eYu=function(h){return h?{style:"background-image: url("+h+")"}:{}},aO2=function(h,W,c){function V(u){u&&(W.listen("blur",function(){u.style.display!="none"&&h.XI&&u.focus()}),W.U(u,"focus",B),W.U(u,"blur",E))}
function H(u){h.S+=u;h.S>0?(g.he(W.element,"ytp-ce-force-expand"),pt(h,c.id,!0)):(g.cD(W.element,"ytp-ce-force-expand"),g.cD(W.element,"ytp-ce-element-hover"),pt(h,c.id,!1))}
function B(){H(1)}
function E(){H(-1)}
W.listen("mouseenter",function(){zYS(h,W,c)});
W.listen("mouseleave",function(){QKK(h,W,c)});
h.player.B().W||W.listen("click",function(){g.he(W.element,"ytp-ce-element-hover")});
W.listen("click",function(u){LBl(h,c,u)});
W.listen("keypress",function(u){LBl(h,c,u)});
W.listen("focus",function(){zYS(h,W,c)});
W.listen("blur",function(){QKK(h,W,c)});
W.listen("touchstart",function(){zYS(h,W,c)});
var J=g.EH("ytp-ce-expanding-overlay-hider",W.element);J&&W.U(J,"touchstart",function(u){u.stopPropagation();g.cD(W.element,"ytp-ce-element-hover");g.cD(W.element,"ytp-ce-force-expand")});
W.listen("keydown",function(u){h.XI=u.keyCode===9&&!u.shiftKey});
V(g.EH("ytp-sb-subscribe",W.element));V(g.EH("ytp-sb-unsubscribe",W.element));W.listen("focus",B);W.listen("blur",E)},LBl=function(h,W,c){if(W.targetUrl&&(!c||c.type!=="keypress"||c.keyCode===13)){for(var V=c.target;V&&!g.k$(V,"ytp-ce-element");){g.k$(V,"subscribe-label")&&iZK(h,W);
if(g.k$(V,"ytp-ce-channel-subscribe"))return;V=V.parentElement||null}if(!V||g.k$(V,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(V=h.W[W.id])QKK(h,V,W),V.element.blur();if(c.ctrlKey||c.metaKey||W.mYf==="new")iZK(h,W),h.player.sendVideoStatsEngageEvent(17,void 0),h.player.pauseVideo(),c=g.Eu(o6(h,W.targetUrl)),c=g.$u(c),g.T3(c,void 0,W.sessionData);else{var H=g.lo(h.player.B())||h.player.getVideoData().B0,B=function(){var E=o6(h,W.targetUrl),J=W.sessionData,u=W.watchEndpoint,d=
g.wO(E);H&&d&&(d.v||d.list)?h.player.Av(d.v,J,d.list,!1,void 0,u||void 0):g.b7(E,J)};
iZK(h,W,function(){h.player.sendVideoStatsEngageEvent(17,B)})}}}},o6=function(h,W){h=h.player.B();
if(W){if(W.startsWith("//"))return h.protocol+":"+W;if(W.startsWith("/"))return g.io(h)+W}else return"";return W},zYS=function(h,W,c){g.k$(W.element,"ytp-ce-element-hover")||(c.type==="VIDEO"||c.type==="PLAYLIST"?g.he(W.element,"ytp-ce-element-hover"):h.player.B().W?(new g.oD(function(){g.he(W.element,"ytp-ce-element-hover")},200)).start():g.he(W.element,"ytp-ce-element-hover"),I6(h,c.YV),pt(h,c.id,!0))},QKK=function(h,W,c){g.cD(W.element,"ytp-ce-element-hover");
g.cD(W.element,"ytp-ce-force-expand");pt(h,c.id,!1)},pt=function(h,W,c){h.G&&(c?h.C.show():h.C.hide());
for(var V=g.e(Object.keys(h.W)),H=V.next();!H.done;H=V.next())H=H.value,H!==W&&g.$y(h.W[H].element,"ytp-ce-element-shadow-show",c)},I6=function(h,W,c){function V(){B||(H++,H===W.length&&(E.stop(),c&&c()))}
if(!W||W.length===0||tV(h))c&&c();else{W=KBc(h,W);var H=0,B=!1,E=new g.oD(function(){B=!0;c&&c()},1E3,h);
E.start();for(h=0;h<W.length;h++)g.Cj(W[h],V)}},iZK=function(h,W,c){I6(h,W.clickUrls,c);
(h=g.q_())&&W.mM&&g.DT(h,W.visualElement)},KBc=function(h,W){var c=h.player.getVideoData().clientPlaybackNonce;
h=h.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:h};h=[];for(var V=0;V<W.length;V++)h.push(AIc(W[V],c));return h},AIc=function(h,W){return h.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var V=unescape(c);
V=V.substring(1,V.length-1);return W[V]?escape(W[V]):c})},UTI=function(h){return typeof h==="string"?h:""},Yo=function(h,W,c){for(var V in W)if(W[V]===h)return h;
return c},CAt=function(h,W,c,V){this.value=h;
this.target=W;this.showLinkIcon=c;this.X=V},Oy=function(h){return h.value?h.value:null},Ss=function(h){if(!h)return null;
var W=g.Eu(UTI(h.value));W=g.$u(W);if(!W)return null;var c=Yo(h.target,MFK,"current");if(c==null)h=null;else{var V=h.show_link_icon;h=new CAt(W,c,V==="true"||V==="false"?V==="true":!0,h.pause_on_navigation!=null?h.pause_on_navigation:!0)}return h},FBl=function(h,W,c){this.type=h;
this.trigger=W;this.url=c},fO6=function(h){if(!h)return null;
var W=Yo(h.type,yIX),c=Yo(h.trigger,PAc);h=h.url;h=Array.isArray(h)&&h.length?h[0]:h;h=Ss(h?h:null);return W?new FBl(W,c,h):null},bZI=function(h,W,c,V,H){this.id=h;
this.type=W;this.style=c;this.data=H;this.action=V||[]},T_f=function(h,W){return g.jl(h.action,W)},N_6=function(h,W){this.context=h;
this.X=W},XX6=function(h){return h.customMessage?gG("div","iv-card-message",h.customMessage):""},D0=function(h,W){h="background-image: url("+h+");";
var c=[];W&&c.push(W);return{D:"div",K:"iv-card-image",J:{style:h},V:c}},tFK=function(h){if(!h.metaInfo||h.metaInfo.length===0)return"";
var W=[];h=g.e(h.metaInfo);for(var c=h.next();!c.done;c=h.next())W.push(gG("li","",c.value));return{D:"ul",K:"iv-card-meta-info",V:W}},gG=function(h,W,c){W?typeof W==="string"?W={"class":W}:Array.isArray(W)&&(W={"class":W.join(" ")}):W={};
W.dir=g.Je(c);return{D:h,J:W,YN:c}},v3S=function(h){if(!h.customMessage)return"";
var W=["iv-card-action","iv-card-primary-link"],c={};h.hY&&(W.push("iv-card-action-icon"),c.style="background-image: url("+h.hY+");");c.dir=g.Je(h.customMessage);var V=[{D:"span",YN:h.customMessage}];h.showLinkIcon&&(V.push("\u00a0"),V.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",LM:W,J:c,V:V}},wG=function(h,W,c,V){if(V){W=g.e(W);
for(var H=W.next();!H.done;H=W.next())h.X(H.value,V,c.id,c.sessionData,c.Gr.click,5)}},mTf=function(h,W){this.merchant=h;
this.price=W},o3t=function(h){var W;
(W=h)&&!(W=h.length>1?h.charAt(0)==="/"&&h.charAt(1)!=="/":h==="/")&&(W=h.replace(/^(https?:)?\/\//,"").split("/",1),W=!W||W.length<1||!W[0]?[]:W[0].toLowerCase().split(".").reverse(),W=W[0]==="com"&&W[1]==="youtube"||W[0]==="be"&&W[1]==="youtu");return W?h.indexOf("/redirect?")===-1:!1},pXX=function(h,W){return W?W:o3t(h)?"current":"new"},ko=function(h,W){g.N.call(this);
var c=this;this.element=h;this.context=W;this.Ef=!1;this.yg=new Map;this.Jk=new Map;this.context.L.addEventListener(g.mZ("annotations_module"),function(V){(V=c.yg.get(V))&&V.apply(c)});
this.context.L.addEventListener(g.om("annotations_module"),function(V){(V=c.Jk.get(V))&&V.apply(c)})},hy=function(h,W,c,V,H,B,E){h.context.X.listen(W,"click",function(J){h.oW(c,V,H,B||[],E||0,J)});
h.context.X.listen(W,"touchstart",function(){h.Ef=!1});
h.context.X.listen(W,"touchmove",function(){h.Ef=!0})},IOI=function(h){var W;
return((W=g.v(h,g.C4))==null?0:W.url)?g.v(h,g.C4).url:(h=g.v(h,g.nC))&&h.videoId?(W="/watch?v="+h.videoId,h.playlistId&&(W+="&list="+h.playlistId),h.index&&(W+="&index="+h.index),h.startTimeSeconds&&(W+="&t="+h.startTimeSeconds),W):null},Wj=function(h,W,c){return{tW:(h.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(V){return V.baseUrl||""}),
close:(W.dismissLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
TC:(W.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
GU:(W.clickLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""})}},YpI=function(h,W,c){ko.call(this,W,c);
var V=this;this.L=h;this.eventId=null;this.lW=this.Nn=this.hI=this.G=this.isInitialized=!1;this.cards=[];this.Ak=this.C=this.mW=this.N=this.Rz=this.X=null;this.XI=[];this.Wk=this.Z=this.c9=this.zV=null;this.S=0;this.DH=new g.oD(function(){},c.uB.VX?4E3:3E3);
g.X(this,this.DH);this.Mn=new g.oD(function(){});
g.X(this,this.Mn);this.Pk=new N_6(c,function(H,B,E,J,u,d){hy(V,H,B,E,J,u,d)});
this.T=new g.p({D:"div",K:"iv-drawer",J:{id:"iv-drawer"},V:[{D:"div",K:"iv-drawer-header",J:{"aria-role":"heading"},V:[{D:"span",K:"iv-drawer-header-text"},{D:"button",LM:["iv-drawer-close-button","ytp-button"],J:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.X(this,this.T);this.Y=this.T.element;this.rE=new g.SL(this.T,330);g.X(this,this.rE);this.uW=g.EH("iv-drawer-header-text",this.Y);this.W=g.EH("iv-drawer-content",this.Y);this.addCueRange(0,c.videoData.lengthSeconds*
1E3,"",function(){V.hI&&cj(V,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(V.hI=V.G)&&VZ(V)});
this.CM=new g.lX(this);g.X(this,this.CM);this.L.addEventListener("videodatachange",this.n$.bind(this))},OZU=function(h,W){W=W.data;
W.autoOpenMs&&h.addCueRange(W.autoOpenMs,0x8000000000000,"",function(){cj(h,"YOUTUBE_DRAWER_AUTO_OPEN")});
W.autoCloseMs&&h.addCueRange(W.autoCloseMs,0x8000000000000,"",function(){VZ(h)});
var c=W.headerText;g.aY(h.uW,c);h.C&&(h.L.j("player_tooltip_data_title_killswitch")?h.C.setAttribute("title",c):h.C.setAttribute("data-tooltip-title",c));W.eventId&&(h.eventId=W.eventId);h.zV=g.GE(W.trackingParams);h.Z=g.GE(W.closeTrackingParams);h.c9=g.GE(W.iconTrackingParams)},SpU=function(h,W){var c=W.cardId?W.cardId:"cr:"+h.S,V=h.L.B().experiments.xN("enable_error_corrections_infocard_web_client");
if(!W.content&&W.teaser.simpleCardTeaserRenderer&&V){var H=W.teaser.simpleCardTeaserRenderer,B=W.icon?W.icon.infoCardIconRenderer:null;if(H.channelAvatar&&H.channelAvatar.thumbnails&&H.channelAvatar.thumbnails.length>0)var E=$r(H.channelAvatar.thumbnails,22,22).url;W={id:c,timestamp:h.S,type:"simple",teaserText:g.EJ(H.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:{},sponsored:!1,Gr:{},NL:null,xC:H.trackingParams?
g.GE(H.trackingParams):null,c9:B&&B.trackingParams?g.GE(B.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,hY:null,title:"",customMessage:"",url:null,onClickCommand:H.onTapCommand||null,hA:E};s8(h,W)}else{var J;if((J=W.content)==null?0:J.simpleCardContentRenderer){if(!W.cueRanges.length)return;E=(H=W.content)==null?void 0:H.simpleCardContentRenderer;H=W.teaser.simpleCardTeaserRenderer;B=W.icon?W.icon.infoCardIconRenderer:null;W={id:c,timestamp:h.S,type:"simple",teaserText:g.EJ(H.message),
teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Hj(h,c,W,E),sponsored:!1,Gr:Wj(E,H,E.command),NL:E.trackingParams?g.GE(E.trackingParams):null,xC:H.trackingParams?g.GE(H.trackingParams):null,c9:B&&B.trackingParams?g.GE(B.trackingParams):null,imageUrl:$r(E.image.thumbnails,290,290).url,displayDomain:E.displayDomain?g.EJ(E.displayDomain):null,showLinkIcon:!!E.showLinkIcon,hY:null,title:E.title?g.EJ(E.title):"",
customMessage:E.callToAction?g.EJ(E.callToAction):"",url:g.v(E.command,g.C4).url?Ss({pause_on_navigation:!h.context.videoData.isLivePlayback,target:"new",value:g.v(E.command,g.C4).url}):null,onClickCommand:null};s8(h,W)}else{var u;if((u=W.content)==null?0:u.collaboratorInfoCardContentRenderer){if(!W.cueRanges.length)return;E=(B=W.content)==null?void 0:B.collaboratorInfoCardContentRenderer;H=W.teaser.simpleCardTeaserRenderer;B=W.icon?W.icon.infoCardIconRenderer:null;W={id:c,timestamp:h.S,type:"collaborator",
teaserText:g.EJ(H.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Hj(h,c,W,E),sponsored:!1,Gr:Wj(E,H,E.endpoint),NL:E.trackingParams?g.GE(E.trackingParams):null,xC:H.trackingParams?g.GE(H.trackingParams):null,c9:B&&B.trackingParams?g.GE(B.trackingParams):null,channelId:g.v(E.endpoint,g.Is).browseId,customMessage:E.customText?g.EJ(E.customText):null,profileImageUrl:$r(E.channelAvatar.thumbnails,290,
290).url,title:E.channelName?g.EJ(E.channelName):"",metaInfo:[E.subscriberCountText?g.EJ(E.subscriberCountText):""],url:Ss({pause_on_navigation:!h.context.videoData.isLivePlayback,target:"new",value:g.v(E.endpoint,g.Is).canonicalBaseUrl?g.v(E.endpoint,g.Is).canonicalBaseUrl:"/channel/"+g.v(E.endpoint,g.Is).browseId}),onClickCommand:null};s8(h,W)}else{var d;if((d=W.content)==null?0:d.playlistInfoCardContentRenderer){if(!W.cueRanges.length)return;var G;E=(G=W.content)==null?void 0:G.playlistInfoCardContentRenderer;
H=W.teaser.simpleCardTeaserRenderer;B=W.icon?W.icon.infoCardIconRenderer:null;W={id:c,timestamp:h.S,type:"playlist",teaserText:g.EJ(H.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Hj(h,c,W,E),sponsored:!1,Gr:Wj(E,H,E.action),NL:E.trackingParams?g.GE(E.trackingParams):null,xC:H.trackingParams?g.GE(H.trackingParams):null,c9:B&&B.trackingParams?g.GE(B.trackingParams):null,fH:$r(E.playlistThumbnail.thumbnails,
258,290).url,customMessage:E.customMessage?g.EJ(E.customMessage):null,playlistVideoCount:g.EJ(E.playlistVideoCount),title:E.playlistTitle?g.EJ(E.playlistTitle):"",metaInfo:[E.channelName?g.EJ(E.channelName):"",E.videoCountText?g.EJ(E.videoCountText):""],url:Ss({pause_on_navigation:!h.context.videoData.isLivePlayback,target:"new",value:IOI(E.action)}),onClickCommand:null};s8(h,W)}else{var Z;if((Z=W.content)==null?0:Z.videoInfoCardContentRenderer){if(!W.cueRanges.length)return;var r;E=(r=W.content)==
null?void 0:r.videoInfoCardContentRenderer;H=W.teaser.simpleCardTeaserRenderer;B=W.icon?W.icon.infoCardIconRenderer:null;W={id:c,timestamp:h.S,type:"video",teaserText:g.EJ(H.message),teaserDurationMs:Number(W.cueRanges[0].teaserDurationMs),startMs:Number(W.cueRanges[0].startCardActiveMs),autoOpen:!!W.autoOpen,sessionData:Hj(h,c,W,E),sponsored:!1,Gr:Wj(E,H,E.action),NL:E.trackingParams?g.GE(E.trackingParams):null,xC:H.trackingParams?g.GE(H.trackingParams):null,c9:B&&B.trackingParams?g.GE(B.trackingParams):
null,fH:$r(E.videoThumbnail.thumbnails,258,290).url,videoDuration:E.lengthString?g.EJ(E.lengthString):null,customMessage:E.customMessage?g.EJ(E.customMessage):null,title:E.videoTitle?g.EJ(E.videoTitle):"",metaInfo:[E.channelName?g.EJ(E.channelName):"",E.viewCountText?g.EJ(E.viewCountText):""],isLiveNow:!!E.badge,url:Ss({pause_on_navigation:!h.context.videoData.isLivePlayback,target:"new",value:IOI(E.action)}),onClickCommand:null};s8(h,W)}}}}}h.S++},$r=function(h,W,c){for(var V=-1,H=-1,B=0;B<h.length;B++){if(h[B].height===
W||h[B].width===c)return h[B];
((h[B].height||0)<W||(h[B].width||0)<c)&&(V<0||(h[V].height||0)<(h[B].height||0)||(h[V].width||0)<(h[B].width||0))?V=B:((h[B].height||0)>=W||(h[B].width||0)>=c)&&(H<0||(h[H].height||0)>(h[B].height||0)||(h[H].width||0)>(h[B].width||0))&&(H=B)}return h[H>=0?H:V]},Hj=function(h,W,c,V){return{feature:c.feature?c.feature:"cards",
src_vid:h.context.videoData.videoId,annotation_id:W,ei:h.context.videoData.eventId||"",itct:V.trackingParams||""}},DT6=function(h,W){if(W=g3l(h,W))W===h.X&&(h.X=null),h.L.removeCueRange(W.g3.id),g.nk(W.u5),g.QU(h.cards,W),h.J8(),Bj(h)},cj=function(h,W,c){if(!h.G){h.rE.show();
h.Rz=new g.oD(function(){g.he(h.context.L.getRootNode(),g.ly.IV_DRAWER_OPEN)},0);
h.Rz.start();h.CM.U(h.W,"mousewheel",function(E){h.DH.start();E.preventDefault();E=E||window.event;var J=0;E.type=="MozMousePixelScroll"?J=0==(E.axis==E.HORIZONTAL_AXIS)?E.detail:0:window.opera?J=E.detail:J=E.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?E.wheelDeltaY/-30:E.wheelDeltaY/-1.2:E.wheelDelta/-1.6:E.wheelDeltaY/-3;if(E=J)h.W.scrollTop+=E});
h.G=!0;var V=g.q_();V&&h.zV&&h.Z&&g.O9(V,[h.zV,h.Z]);W={TRIGGER_TYPE:W};for(var H=g.e(h.cards),B=H.next();!B.done;B=H.next())B=B.value,B.Ir||(B.Ir=!0,wXc(h.context.logger,B.g3.Gr.tW,W)),V&&g.O9(V,[B.g3.NL]);My(h.L);c&&(h.N=new g.oD(function(){h.mW=h.C;h.Ak.focus()},330),h.N.start())}},VZ=function(h){h.G&&(h.rE.hide(),g.zR(h.CM),g.cD(h.context.L.getRootNode(),g.ly.IV_DRAWER_OPEN),h.G=!1,My(h.L),h.N&&h.N.stop(),h.N=new g.oD(function(){h.mW&&(h.mW.focus(),h.mW=null)},330),h.N.start())},kmU=function(h){g.WD(h.fJ(),
[g.ly.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ge(h.L,h.Y,5);h.NI();h.C=g.EH("ytp-cards-button",h.L.getRootNode());h.Ak=g.EH("iv-drawer-close-button",h.Y);h.isInitialized=!0},hr6=function(h){h.XI.push(g.S5("iv-teaser-shown",h.pS,h));
h.XI.push(g.S5("iv-teaser-hidden",h.E1,h));h.XI.push(g.S5("iv-teaser-clicked",h.tS,h));h.lW=!0},Wu2=function(h,W){var c;
return W.onClickCommand&&((c=g.v(W.onClickCommand,g.M8I))==null?void 0:c.targetId)==="engagement-panel-error-corrections"?(h.Wk=W,!0):!1},cqK=function(h,W){h.Wk=W;
var c=h.L.getVideoData();if(!c)return!1;c=g.gu(c);if(c==null?0:c.markersMap)for(var V,H=0;((V=c)==null?void 0:V.markersMap.length)>H;H++){var B=void 0,E=(B=c)==null?void 0:B.markersMap[H];if(E.key==="ERROR_CORRECTION_MARKERS"&&(B=void 0,(E=(B=E.value)==null?void 0:B.markers)&&E.length>0))return V=void 0,W.startMs=((V=g.v(E[0],g.$4L))==null?void 0:V.timeRangeStartMillis)||0,h.Wk=null,!0}return!1},s8=function(h,W){if(!Wu2(h,W)||cqK(h,W)){var c=Vpf(h,W);
if(c){var V={g3:W,u5:c.element,Ir:!1};if(W.onClickCommand)h.L.j("web_infocards_teaser_show_logging_fix")&&(h.lW||hr6(h),DT6(h,W.id),c=h.findLastIndex(V),g.X6(h.cards,c,0,V));else{h.isInitialized||kmU(h);DT6(h,W.id);var H=h.findLastIndex(V);g.X6(h.cards,H,0,V);c.kN(h.W,H);h.J8()}W.autoOpen?h.addCueRange(W.startMs,0x8000000000000,W.id,function(){h.G||(h.X=V,Bj(h),$3K(h,V),cj(h,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=h.context.L.getCurrentTime()*1E3,c<5E3&&c>W.startMs&&sV2(h,V),h.addCueRange(W.startMs,
W.startMs+1,W.id,function(){sV2(h,V)}),Bj(h))}}},Vpf=function(h,W){switch(W.type){case "simple":h=h.Pk;
var c=W.displayDomain?{D:"div",K:"iv-card-image-text",YN:W.displayDomain}:void 0;var V=v3S(W);c={D:"div",LM:["iv-card"],V:[{D:"a",K:"iv-click-target",J:{href:W.url?Oy(W.url)||"":""},V:[D0(W.imageUrl,c),{D:"div",K:"iv-card-content",V:[gG("h2",void 0,W.title),V]}]}]};c=new g.p(c);wG(h,g.H3("iv-click-target",c.element),W,W.url);W=c;break;case "collaborator":h=h.Pk;c={D:"div",LM:["iv-card","iv-card-channel"],V:[{D:"a",LM:["iv-click-target"],J:{href:Oy(W.url)||"","data-ytid":W.channelId},V:[D0(W.profileImageUrl),
{D:"div",K:"iv-card-content",V:[XX6(W),{D:"h2",K:"iv-card-primary-link",YN:W.title},tFK(W)]}]}]};c=new g.p(c);wG(h,g.H3("iv-click-target",c.element),W,W.url);W=c;break;case "playlist":h=h.Pk;c={D:"div",LM:["iv-card","iv-card-playlist"],V:[{D:"a",K:"iv-click-target",J:{href:Oy(W.url)||""},V:[D0(W.fH,{D:"div",K:"iv-card-image-overlay",V:[{D:"span",K:"iv-card-playlist-video-count",YN:W.playlistVideoCount}]}),{D:"div",K:"iv-card-content",V:[XX6(W),gG("h2","iv-card-primary-link",W.title),tFK(W)]}]}]};
c=new g.p(c);wG(h,g.H3("iv-click-target",c.element),W,W.url);W=c;break;case "productListing":h=h.Pk;var H=W.offers.length!=0;c=["iv-card"];V="";var B=v3S(W);H&&(c.push("iv-card-product-listing"),V="iv-card-primary-link",B=W.offers[0],H=[],B.price&&H.push({D:"div",K:"iv-card-offer-price",YN:B.price}),B.merchant&&H.push({D:"div",K:"iv-card-offer-merchant",YN:B.merchant}),B={D:"div",V:H});H=W.url?Oy(W.url)||"":"";c={D:"div",LM:c,J:{tabindex:"0"},V:[{D:"a",LM:["iv-card-image","iv-click-target"],J:{style:"background-image: url("+
W.imageUrl+");",href:H,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",V:[W.sponsored?{D:"div",K:"iv-card-sponsored",V:["Sponsored",{D:"div",K:"iv-ad-info-container",V:[{D:"div",K:"iv-ad-info",YN:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",V:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",J:{href:H},V:[gG("h2",V,W.title),B]}]}]};c=new g.p(c);V=g.Zr("span");g.aY(V,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.rW(V,"adInfo");wG(h,g.H3("iv-click-target",c.element),W,W.url);W=c;break;case "video":h=h.Pk;V=W.videoDuration?{D:"span",K:"iv-card-video-duration",YN:W.videoDuration}:void 0;B=W.isLiveNow?{D:"span",LM:["yt-badge","yt-badge-live"],YN:"LIVE NOW"}:null;H={D:"div",LM:["iv-card","iv-card-video"],V:[{D:"a",K:"iv-click-target",J:{href:((c=W.url)==null?void 0:Oy(c))||""},V:[D0(W.fH,V),{D:"div",K:"iv-card-content",V:[XX6(W),gG("h2","iv-card-primary-link",W.title),tFK(W),B]}]}]};c=new g.p(H);wG(h,g.H3("iv-click-target",
c.element),W,W.url);W=c;break;default:return null}return W},H7U=function(h){if(h.X)return h.X.g3.type==="productListing";
if(h.L.j("enable_wn_infocards")){var W;return!((W=h.cards)==null||!W.length)&&g.l6(h.cards,function(c){return c.g3.type==="productListing"})}return g.l6(h.cards,function(c){return c.g3.type==="productListing"})},Bj=function(h){g.$y(h.L.getRootNode(),"ytp-cards-shopping-active",H7U(h))},sV2=function(h,W){if(!g.k$(h.L.getRootNode(),"ytp-cards-teaser-shown")){if(h.X!==W){var c=g.q_(),V=h.X?h.X.g3.c9:h.c9;
c&&V&&g.S2(c,[V]);h.X=W;Bj(h)}(c=h.isInitialized&&h.fJ().style.display=="none")||(c=h.context.L.getPlayerState(),V=c===0&&h.context.L.getCurrentTime()===0,c=!(c===1||c===3||V));if(!c&&W.g3.teaserDurationMs){var H;c={teaserText:W.g3.teaserText,durationMs:W.g3.teaserDurationMs,onClickCommand:W.g3.onClickCommand,hA:(H=W.g3.hA)!=null?H:null};h.L.uo(!0,c)}h.Mn.isActive()||((!h.G||!h.DH.isActive()&&h.Nn)&&$3K(h,W),h.Mn.start(910+W.g3.teaserDurationMs))}},$3K=function(h,W){h.T.Of?(W=new bE([0,
h.W.scrollTop],[0,W.u5.offsetTop],600,dTK),h.context.G.listen(W,"animate",function(c){h.W.scrollTop=c.y}),h.context.G.listen(W,"finish",function(c){h.W.scrollTop=c.y}),W.play()):(h.T.pJ(!0),h.W.scrollTop=W.u5.offsetTop,h.T.pJ(!1))},E8=function(h){return h.X&&h.X.g3?h.X.g3:h.cards[0]&&h.cards[0].g3?h.cards[0].g3:null},g3l=function(h,W){return g.jl(h.cards,function(c){return c.g3.id===W})},Rz=function(h,W,c){ko.call(this,h,W);
this.annotation=c;this.isActive=!1},BiX=function(h){var W=h.annotation.data;
"start_ms"in W&&"end_ms"in W&&h.addCueRange(Number(W.start_ms),Number(W.end_ms),h.annotation.id,function(){h.show()},function(){h.hide()})},Jy=function(h,W,c){Rz.call(this,h,W,c);
this.W=null;this.S=!1;this.G=null;this.Y=!1;this.X=this.N=this.C=null},EL6=function(h,W){var c=c===void 0?0:c;
var V=VFU(W).width;g.gb(W,V);c=new JIt(W,[V,W.offsetTop],[V-V-c,W.offsetTop],200,uxf);g.X(h,c);h.context.G.listen(c,"begin",function(){g.cW(W,!0)});
c.play()},uM2=function(h,W){if(W.channel_name){var c=h.createElement({D:"div",
LM:["iv-branding-context-name"],YN:W.channel_name}),V=h.createElement({D:"div",LM:["iv-branding-context-subscribe"]}),H=W.standalone_subscribe_button_data;H&&(h.X=new g.Hm(H.subscribeText,H.subscribeCount,H.unsubscribeText,H.unsubscribeCount,!!H.enabled,!!H.classic,W.channel_id,!!H.subscribed,H.feature,W.session_data.itct,h.context.L,!1),h.X.kN(V));var B=h.createElement({D:"div",LM:["iv-branding-context-subscribe-caret"]}),E=h.createElement({D:"div",LM:["branding-context-container-inner"]});E.appendChild(B);
E.appendChild(c);E.appendChild(V);g.cW(E,!1);var J=h.createElement({D:"div",LM:["branding-context-container-outer"]});J.appendChild(E);g.oY(J,"right",W.image_width+"px");g.qJ(h.fJ(),J);h.G=new g.oD(function(){RrS(h,E,J)},500);
g.X(h,h.G);h.context.X.listen(h.fJ(),"mouseover",function(){Jq2(h,E,J,B,W.image_height)});
h.context.X.listen(h.fJ(),"mouseout",function(){h.G.start()})}},Jq2=function(h,W,c,V,H){h.G.stop();
if(!h.Y){var B=g.WW(W);h.X||(W.style.width=g.Sk(B.width,!0),c.style.width=g.Sk(B.width,!0));g.oY(V,"top",B.height-Math.max(Math.min(B.height,H)/2+10,20)+"px");g.oY(V,"right","1px");h.Y=!0;g.cW(W,!0);h.C=new g.oD(function(){g.he(this.fJ(),"iv-branding-active")},0,h);
h.C.start()}},RrS=function(h,W,c){g.cD(h.fJ(),"iv-branding-active");
h.N=new g.oD(function(){g.cW(W,!1);h.X||(c.style.width=g.Sk(0,!0))},250);
h.N.start();h.Y=!1},d3U=function(h,W,c,V,H,B,E){this.X=h;
this.G=W;this.uB=c;this.videoData=V;this.logger=H;this.L=B;this.W=E},G0U=function(h,W,c){Rz.call(this,h,W,c);
var V=this;this.Z=this.isCollapsed=this.T=!1;this.N=5E3;this.W=this.G=this.X=this.Y=null;this.S=this.createElement({D:"div",LM:["iv-promo-contents"]});this.C=new g.oD(function(){V.X.setAttribute("aria-hidden","true");g.cW(V.G,!1);g.cW(V.W,!0)},700,this);
g.X(this,this.C)},rq2=function(h){var W=h.annotation.data;
if(h.annotation.style==="cta")var c=6;else if(h.annotation.style==="video"||h.annotation.style==="playlist")c=7;h.N=W.collapsedelay_ms||h.N;var V=["iv-promo","iv-promo-inactive"];h.fJ().setAttribute("aria-hidden","true");h.fJ().setAttribute("aria-label","Promotion");h.fJ().tabIndex=0;var H=h.annotation.Ly(),B=W.image_url;if(B){var E=h.createElement({D:"div",LM:["iv-promo-img","iv-click-target"]});B=h.createElement({D:"img",J:{src:B,"aria-hidden":"true"}});E.appendChild(B);W.video_duration&&!W.is_live?
(B=h.createElement({D:"span",K:"iv-promo-video-duration",YN:W.video_duration}),E.appendChild(B)):W.playlist_length&&(B=h.createElement({D:"span",K:"iv-promo-playlist-length",YN:W.playlist_length.toString()}),E.appendChild(B));H&&hy(h,E,H,h.annotation.id,W.session_data,void 0,c)}H?(B=h.createElement({D:"a",K:"iv-promo-txt"}),g.u4(B,Oy(H)),h.X=B):h.X=h.createElement({D:"div",K:"iv-promo-txt"});switch(h.annotation.style){case "cta":case "website":var J=h.createElement({D:"p",V:[{D:"strong",YN:W.text_line_1}]});
var u=h.createElement({D:"p",V:[{D:"span",K:"iv-promo-link",YN:W.text_line_2}]});if(B=W.text_line_3){V.push("iv-promo-website-card-cta-redesign");var d=h.createElement({D:"button",LM:["iv-promo-round-expand-icon","ytp-button"]});B=h.createElement({D:"button",LM:["iv-button","iv-promo-button"],V:[{D:"span",K:"iv-button-content",YN:B}]});var G=h.createElement({D:"div",K:"iv-promo-button-container"});G.appendChild(B);H&&hy(h,h.fJ(),H,h.annotation.id,W.session_data,void 0,c)}g.he(h.X,"iv-click-target");
H&&hy(h,h.X,H,h.annotation.id,W.session_data,void 0,c);break;case "playlist":case "video":J=h.createElement({D:"p",V:[{D:"span",YN:W.text_line_1}]}),u=h.createElement({D:"p",V:[{D:"strong",YN:W.text_line_2}]}),W.is_live&&(J=u,u=h.createElement({D:"span",LM:["yt-badge","iv-promo-badge-live"],YN:"LIVE NOW"})),g.he(h.X,"iv-click-target"),H&&hy(h,h.X,H,h.annotation.id,W.session_data,void 0,c),V.push("iv-promo-video")}J&&h.X.appendChild(J);u&&h.X.appendChild(u);h.S.appendChild(h.X);G&&h.S.appendChild(G);
c=h.createElement({D:"div",K:"iv-promo-actions"});h.W=h.createElement({D:"button",LM:["iv-promo-expand","ytp-button"]});h.W.title="Expand";h.context.X.listen(h.W,"click",function(Z){Z7l(h,5E3,Z)});
c.appendChild(h.W);g.cW(h.W,!1);h.context.X.listen(h.fJ(),"mouseover",h.oY,h);h.context.X.listen(h.fJ(),"mouseout",h.Uo,h);h.context.X.listen(h.fJ(),"touchend",function(Z){Z7l(h,5E3,Z)});
h.G=h.createElement({D:"button",LM:["iv-promo-close","ytp-button"]});h.G.title="Close";h.context.X.listen(h.G,"click",h.annotation.style==="cta"&&W.text_line_3?h.RY:h.SY,h);c.appendChild(h.G);g.WD(h.fJ(),V);E&&(g.qJ(h.fJ(),E),d&&E.appendChild(d));g.qJ(h.fJ(),h.S);g.qJ(h.fJ(),c)},Z7l=function(h,W,c){c.stopPropagation();
qWl(h);x3t(h,W);h.X.focus()},l4U=function(h){h.isCollapsed||h.Z||h.Y||(g.he(h.fJ(),"iv-promo-collapsed"),h.isCollapsed=!0,h.C.start())},qWl=function(h){h.C.stop();
h.isCollapsed&&(g.V$(h.fJ(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),h.isCollapsed=!1,h.X&&h.X.removeAttribute("aria-hidden"),g.cW(h.W,!1),g.cW(h.G,!0))},x3t=function(h,W){h.Y||(h.Y=g.PK(function(){nLS(this);
l4U(this)},W,h))},nLS=function(h){h.Y&&(g.k5.clearTimeout(h.Y),h.Y=null)},jV2=function(h){this.L=h},wXc=function(h,W,c){W&&(c?uP(h,W.map(function(V){return g.Q8(V,c)})):uP(h,W))},uP=function(h,W,c,V){var H=1,B=void 0,E=-1;
if(c){var J=!1;B=function(){H--;H||J||(clearTimeout(E),J=!0,c())};
E=setTimeout(function(){J=!0;c()},1E3)}W=g.e(W||[]);
for(var u=W.next();!u.done;u=W.next())u=u.value,H++,g.Cj(u,B);V&&(H++,V!==0&&h.L.sendVideoStatsEngageEvent(V,B))},a4U=function(h){g.K3.call(this,h);
var W=this;this.XI=this.Z=!1;this.loadNumber=0;this.N={};this.logger=new jV2(this.player);this.Y=new g.lX(this);this.C=this.S=null;this.events=new g.lX(this);this.iJ=this.T=this.X=null;this.Wk=[];g.X(this,this.Y);this.Y.U(this.player,"onVideoAreaChange",function(){W.publish("onVideoAreaChange")});
this.Y.U(this.player,"onHideControls",function(){W.publish("onHideControls")});
this.Y.U(this.player,"onShowControls",function(){W.publish("onShowControls")});
this.Y.U(this.player,"resize",function(V){W.publish("resize",V)});
this.Y.U(this.player,"presentingplayerstatechange",function(V){W.publish("presentingplayerstatechange",V)});
this.subscribe("presentingplayerstatechange",this.Bg,this);this.subscribe("resize",this.oA,this);this.player.B().Nn.subscribe("vast_info_card_add",this.G9,this);g.X(this,this.events);this.Pk=this.createElement({D:"div",K:"video-custom-annotations"});this.W=new g.p({D:"div",LM:["ytp-player-content","ytp-iv-player-content"]});g.X(this,this.W);g.ge(this.player,this.W.element,4);this.W.hide();this.G=new g.p({D:"div",LM:["ytp-iv-video-content"]});g.X(this,this.G);h=this.createElement({D:"div",K:"video-annotations"});
h.appendChild(this.Pk);this.G.element.appendChild(h);this.Sb()&&this.load();var c=this.createElement({D:"style"});(g.sH("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.nk(c)});
if(h=c.sheet)h.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),h.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),h.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),h.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),h.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),h.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),h.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),h.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),h.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),h.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},er2=function(h){h=h.createElement({D:"div",
LM:["annotation","annotation-type-custom"]});g.cW(h,!1);return h},zr6=function(h,W){W=!W.isCued()&&!g.Y(W,1024);
h.W.pJ(W);h.G.pJ(W)},QV6=function(h,W,c){h.Z=!0;
h.C=g.nb(W,c)},Lu2=function(h,W){for(var c={},V=g.e(W.attributes),H=V.next();!H.done;H=V.next())H=H.value,c[H.name]=H.nodeValue;
for(V=0;V<W.childNodes.length;V++)if(H=W.childNodes[V],g.H2(H)&&H.nodeType==1){if(c[H.tagName])var B=c[H.tagName];else if(H.tagName==="data"){H.childNodes.length>0&&(B=H.childNodes[0].nodeValue,c[H.tagName]=typeof B==="string"?B.trim():B);continue}else B=[],c[H.tagName]=B;H&&H.tagName==="TEXT"?H.childNodes.length===1&&H.childNodes[0].nodeType===3?B.push(H.childNodes[0].nodeValue):B.push(""):H&&B.push(Lu2(h,H))}return c},U3$=function(h){var W=h.player.getVideoData();
if(W.CM){var c=h.player.B().Nn.get(W.videoId);if(c){var V={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(H,B,E){H=h.loadNumber;B=W.videoId;h.loaded&&h.loadNumber===H&&h.player.getVideoData().videoId===B&&(E=g.EB(E)&&E.responseXML?E.responseXML:null)&&i7f(h,E)}};
g.St()&&(V.onFinish=KuU(h,V.onFinish));V.postParams={ic_only:"1"};Aq2(V,c);h.Z=!0;g.nb(W.CM,V)}}},Aq2=function(h,W){h.method="POST";
h.postParams=h.postParams||{};W.Bz&&(h.postParams.ic_coll=W.Bz);W.l5&&(h.postParams.ic_xml=W.l5);W.Ll&&(h.postParams.ic_track=W.Ll)},Crt=function(h){var W=new g.p({D:"div"});
g.cW(W.element,!1);var c=new YpI(h.player,W.element,dp(h));g.X(c,W);W.kN(h.W.element);c.BF();return c},Fuc=function(h,W){var c,V;
if(W=(c=W.getWatchNextResponse())==null?void 0:(V=c.cards)==null?void 0:V.cardCollectionRenderer)h.XI=!0,Mpf(h,W),W.headerText&&h.iJ&&(c=g.EJ(W.headerText),h.player.j("player_tooltip_data_title_killswitch")?h.iJ.setAttribute("title",c):h.iJ.setAttribute("data-tooltip-title",c))},dp=function(h){if(!h.T){var W=new GmU(h);
g.X(h,W);var c=new g.dH(h);g.X(h,c);h.T=new d3U(W,c,h.player.B(),h.player.getVideoData(),h.logger,h.player,h.hG)}return h.T},i7f=function(h,W){var c=!1,V=W.getElementsByTagName("annotations");
if(V&&!(V.length<1)&&(V=V[0].getAttribute("itct"))){var H=g.q_();if(H){var B=g.rc();B&&g.IW(g.bD)(void 0,H,B,[g.GE(V)])}}W=W.getElementsByTagName("annotation");for(V=0;V<W.length;V++){B=Lu2(h,W[V]);H=null;try{if(B){var E=B.id,J=/.+/;var u=typeof E==="string"&&J!=null&&E!=null&&E.match(J)?E:"";var d=Yo(B.type,yq2),G=Yo(B.style,PrS),Z=UTI(B.data),r=Z.length!==0?JSON.parse(Z):{};var q=B.action;B=fO6;if(q==null)var x=null;else if(g.sI(q)){J=[];for(var z=g.e(q),L=z.next();!L.done;L=z.next()){var M=B(L.value);
M&&J.push(M)}x=J}else{var U=B(q);x=U?[U]:[]}H=u&&d?new bZI(u,d,G,x,r):null}else H=null}catch(Bd){}if(H)if(H.type==="branding"||H.type==="promotion"){B=h;J=H;var y=er2(B),T=null;switch(J.type){case "branding":if(B.player.B().iX)break;B.player.j("web_player_overlay_positioned_layout")?(y.setAttribute("data-overlay-order","11"),B.player.iO(y,4,!0)):B.W.element.appendChild(y);T=new Jy(y,dp(B),J);break;case "promotion":g.ge(B.player,y,4),T=new G0U(y,dp(B),J)}T&&T.BF();if(B=T)g.X(h,B),h.N[H.id]=B}else if(H.type===
"card"||H.type==="drawer"){h.X||(h.X=Crt(h),g.X(h,h.X));if(H.type==="card"){y=h.X;var m=(c=H)&&c.data&&c.data.card_type;H=c.data;if(m)switch(B=H.tracking||{},B={tW:B.impression,click:B.click,close:B.close,TC:B.teaser_impression,GU:B.teaser_click},J=H.tracking_params||{},T=null,m){case "collaborator":c={id:c.id,timestamp:H.timestamp||0,type:H.card_type,teaserText:H.teaser_text,teaserDurationMs:H.teaser_duration_ms,startMs:H.start_ms,autoOpen:H.auto_open||!1,sessionData:H.session_data||{},sponsored:H.sponsored||
!1,Gr:B,NL:J.card?g.GE(J.card):null,xC:J.teaser?g.GE(J.teaser):null,c9:J.icon?g.GE(J.icon):null,channelId:H.channel_id,customMessage:H.custom_message?H.custom_message:null,profileImageUrl:H.image_url,title:H.title,metaInfo:H.meta_info,url:Ss({pause_on_navigation:H.pause_on_navigation,target:H.target||"new",value:H.url}),onClickCommand:null};s8(y,c);break;case "playlist":c={id:c.id,timestamp:H.timestamp||0,type:H.card_type,teaserText:H.teaser_text,teaserDurationMs:H.teaser_duration_ms,startMs:H.start_ms,
autoOpen:H.auto_open||!1,sessionData:H.session_data||{},sponsored:H.sponsored||!1,Gr:B,NL:J.card?g.GE(J.card):null,xC:J.teaser?g.GE(J.teaser):null,c9:J.icon?g.GE(J.icon):null,fH:H.image_url,playlistVideoCount:H.playlist_video_count,customMessage:H.custom_message?H.custom_message:null,title:H.title,metaInfo:H.meta_info,url:Ss({pause_on_navigation:H.pause_on_navigation,target:H.target||"new",value:H.url}),onClickCommand:null};s8(y,c);break;case "productListing":H.signin_url&&(T=Ss({target:"current",
value:H.signin_url}));m=[];for(var D=H.offers||[],O=0;O<D.length;O++)m.push(new mTf(g.Fk(D[O].merchant),g.Fk(D[O].price)));c={id:c.id,timestamp:H.timestamp||0,type:H.card_type,teaserText:H.teaser_text,teaserDurationMs:H.teaser_duration_ms,startMs:H.start_ms,autoOpen:H.auto_open||!1,sessionData:H.session_data||{},sponsored:H.sponsored||!1,Gr:B,NL:J.card?g.GE(J.card):null,xC:J.teaser?g.GE(J.teaser):null,c9:J.icon?g.GE(J.icon):null,imageUrl:H.image_url,displayDomain:H.display_domain?H.display_domain:
null,showLinkIcon:!!H.show_link_icon,hY:H.button_icon_url?H.button_icon_url:null,title:H.title,customMessage:H.custom_message?H.custom_message:null,url:Ss({pause_on_navigation:H.pause_on_navigation,target:H.target||"new",value:H.url}),fiB:T,viE:H.signin_title?H.signin_title:void 0,PRV:H.signin_message?H.signin_message:void 0,offers:m,onClickCommand:null};s8(y,c);break;case "simple":c={id:c.id,timestamp:H.timestamp||0,type:H.card_type,teaserText:H.teaser_text,teaserDurationMs:H.teaser_duration_ms,
startMs:H.start_ms,autoOpen:H.auto_open||!1,sessionData:H.session_data||{},sponsored:H.sponsored||!1,Gr:B,NL:J.card?g.GE(J.card):null,xC:J.teaser?g.GE(J.teaser):null,c9:J.icon?g.GE(J.icon):null,imageUrl:H.image_url,displayDomain:H.display_domain?H.display_domain:null,showLinkIcon:!!H.show_link_icon,hY:H.button_icon_url?H.button_icon_url:null,title:H.title,customMessage:H.custom_message?H.custom_message:null,url:Ss({pause_on_navigation:H.pause_on_navigation,target:H.target||"new",value:H.url}),onClickCommand:null};
s8(y,c);break;case "video":c={id:c.id,timestamp:H.timestamp||0,type:H.card_type,teaserText:H.teaser_text,teaserDurationMs:H.teaser_duration_ms,startMs:H.start_ms,autoOpen:H.auto_open||!1,sessionData:H.session_data||{},sponsored:H.sponsored||!1,Gr:B,NL:J.card?g.GE(J.card):null,xC:J.teaser?g.GE(J.teaser):null,c9:J.icon?g.GE(J.icon):null,fH:H.image_url,videoDuration:H.video_duration||null,customMessage:H.custom_message?H.custom_message:null,title:H.title,metaInfo:H.meta_info,isLiveNow:!!H.is_live_now,
url:Ss({pause_on_navigation:H.pause_on_navigation,target:H.target||"new",value:H.url}),onClickCommand:null},s8(y,c)}}else OZU(h.X,H);c=!0}}c&&(My(h.player),h.oA())},Mpf=function(h,W){var c=!1;
h.X||(h.X=Crt(h),g.X(h,h.X));for(var V=g.e(W.cards||[]),H=V.next();!H.done;H=V.next())H=H.value,H.cardRenderer&&(SpU(h.X,H.cardRenderer),c=!0);if(c){var B;(B=h.player.getVideoData())!=null&&g.kq(B)||(c=h.X,V=W.headerText?g.EJ(W.headerText):"",g.aY(c.uW,V),c.C&&(c.L.j("player_tooltip_data_title_killswitch")?c.C.setAttribute("title",V):c.C.setAttribute("data-tooltip-title",V)),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.zV=W.trackingParams?g.GE(W.trackingParams):null,c.Z=
W.closeButton.infoCardIconRenderer.trackingParams?g.GE(W.closeButton.infoCardIconRenderer.trackingParams):null,c.c9=W.icon.infoCardIconRenderer.trackingParams?g.GE(W.icon.infoCardIconRenderer.trackingParams):null,h.oA());My(h.player)}},f46=function(h,W,c,V,H){if(!h.player.B().iX){var B=[];
W.navigationEndpoint&&g.v(W.navigationEndpoint,g.Is)&&g.v(W.navigationEndpoint,g.Is).browseId&&B.push(new FBl("openUrl","click",new CAt("/channel/"+g.v(W.navigationEndpoint,g.Is).browseId,"new",!0,!0)));var E=W.watermark.thumbnails[0];V={channel_name:W.channelName,end_ms:W.endTimeMs,image_height:E.height,image_type:1,image_url:E.url,image_width:E.width,is_mobile:!1,session_data:{annotation_id:c,ei:H,feature:"iv",itct:W.trackingParams,src_vid:V},start_ms:W.startTimeMs};if(W.subscribeButton&&g.v(W.subscribeButton,
g.Yq)){V.channel_id=g.v(W.subscribeButton,g.Yq).channelId;var J;W=g.v(W.subscribeButton,g.Yq);E=H=null;W.subscribed?(W.subscriberCountWithUnsubscribeText&&(H=g.EJ(W.subscriberCountWithUnsubscribeText)),W.subscriberCountText&&(E=g.EJ(W.subscriberCountText))):(W.subscriberCountText&&(H=g.EJ(W.subscriberCountText)),W.subscriberCountWithSubscribeText&&(E=g.EJ(W.subscriberCountWithSubscribeText)));var u,d=((u=g.v((J=W.signInEndpoint)==null?void 0:J.commandMetadata,g.i5))==null?void 0:u.url)||"";J={subscribeText:g.EJ(W.unsubscribedButtonText),
subscribeCount:H||"",unsubscribeText:g.EJ(W.subscribedButtonText),unsubscribeCount:E||"",enabled:W.enabled||!1,classic:!1,subscribed:W.subscribed||!1,feature:"iv",signInUrl:d};V.standalone_subscribe_button_data=J}B=new bZI(c,"branding","branding",B,V);J=er2(h);h.player.j("web_player_overlay_positioned_layout")?(J.setAttribute("data-overlay-order","11"),h.player.iO(J,4,!0)):h.W.element.appendChild(J);B=new Jy(J,dp(h),B);B.BF();g.X(B,B);h.N[c]=B}},KuU=function(h,W){return function(){var c=g.tN.apply(0,
arguments);
h.gE()||h.Wk.push(g.Py.rp(function(){W.apply(null,g.rN(c))}))}},b7u=function(h){return h==="annotation-editor"||h==="live-dashboard"};
g.t7.prototype.uo=g.$5(39,function(h,W){var c=g.XV(this.Pi());c&&c.uo(h,W)});
var yS={},P$=null;g.rX(bE,g.sb);g.l=bE.prototype;g.l.getDuration=function(){return this.duration};
g.l.play=function(h){if(h||this.X==0)this.progress=0,this.coords=this.W;else if(this.isPlaying())return!1;ft(this);this.startTime=h=g.Gt();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.Y=this.startTime;this.progress||this.Nw();this.L9("play");this.isPaused()&&this.L9("resume");this.X=1;var W=g.EI(this);W in yS||(yS[W]=this);HZ6();B_f(this,h);return!0};
g.l.stop=function(h){ft(this);this.X=0;h&&(this.progress=1);E3$(this,this.progress);this.onStop();this.J7()};
g.l.pause=function(){this.isPlaying()&&(ft(this),this.X=-1,this.L9("pause"))};
g.l.dE=function(){this.X==0||this.stop(!1);this.L9("destroy");bE.Ms.dE.call(this)};
g.l.destroy=function(){this.dispose()};
g.l.U9=function(){this.L9("animate")};
g.l.L9=function(h){this.dispatchEvent(new RYI(h,this))};
g.rX(RYI,g.mm);g.rX(TD,bE);TD.prototype.G=function(){};
TD.prototype.U9=function(){this.G();TD.Ms.U9.call(this)};
TD.prototype.J7=function(){this.G();TD.Ms.J7.call(this)};
TD.prototype.Nw=function(){this.G();TD.Ms.Nw.call(this)};
g.rX(JIt,TD);JIt.prototype.G=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.n(GmU,g.N);g.l=GmU.prototype;g.l.listen=function(h,W,c,V){c=(0,g.JS)(c,V||this.W);h=g.qz(h,W,c);this.X.push(h);return h};
g.l.Ya=function(h,W,c,V){c=(0,g.JS)(c,V||this.W);h=$Tt(h,W,c);this.X.push(h);return h};
g.l.v0=function(h){g.xk(h);g.QU(this.X,h)};
g.l.removeAll=function(){g.xk(this.X);this.X.length=0};
g.l.dE=function(){this.removeAll();g.N.prototype.dE.call(this)};g.n(qpf,g.K3);g.l=qpf.prototype;g.l.load=function(){g.K3.prototype.load.call(this);if(!tV(this)){var h=g.S2Q(this.player.getVideoData());h?(h=rI2(h,xTX(this)),v$(this,h,!1)):lOc(this)}};
g.l.unload=function(){v$(this,null);this.Y&&(this.Y.abort(),this.Y=null);g.K3.prototype.unload.call(this)};
g.l.Et=function(h,W){return tV(this)?h==="loadCustomEndscreenRenderer"?(h=rI2(W,"new"),v$(this,h),!0):null:null};
g.l.getOptions=function(){return tV(this)?["loadCustomEndscreenRenderer"]:[]};
g.l.I1=function(){if(this.endscreen&&this.endscreen.elements){var h=this.player.getVideoContentRect();if(h&&h.width!==0&&h.height!==0){var W=this.player.getPlayerSize();if(W&&W.width!==0&&W.height!==0){var c=h.width/h.height;var V=0;for(var H=-1,B=0;B<Ti6.length;B++){var E=Math.abs(W.width-Ti6[B]);if(H===-1||V>=E)H=B,V=E}V=NiU[H];this.G&&g.oY(this.G.element,"outline-width",Math.max(W.width,W.height)+"px");for(W=0;W<this.endscreen.elements.length;++W)if(B=this.endscreen.elements[W].id,H=this.W[B],
E=this.N[B],H&&E){var J=E.width*c/E.aspectRatio,u=Math.round(E.width*h.width);B=Math.round(J*h.height);var d=h.left+Math.round(E.left*h.width),G=h.top+Math.round(E.top*h.height);g.h3(H.element,u,B);g.gb(H.element,d,G);g.V$(H.element,Xot);u>256||B>256?g.he(H.element,"ytp-ce-large-round"):u>96||B>96?g.he(H.element,"ytp-ce-medium-round"):g.he(H.element,"ytp-ce-small-round");g.V$(H.element,tpt);u=E.left+E.width/2;E=E.top+J/2;g.he(H.element,u<=.5&&E<=.5?"ytp-ce-top-left-quad":u>.5&&E<=.5?"ytp-ce-top-right-quad":
u<=.5&&E>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.V$(H.element,NiU);g.he(H.element,V);(H=g.B3(document,"div","ytp-ce-expanding-overlay-body",H.element)[0])&&g.oY(H,"height",B+"px")}}}}};
g.l.onCueRangeEnter=function(h){if(this.endscreen)if(h.getId()==="ytp-ce-in-endscreen")I6(this,this.endscreen.impressionUrls),(h=g.q_())&&this.endscreen.visualElement&&g.YN(h,this.endscreen.visualElement),this.X&&(g.he(this.X,"ytp-ce-element-show"),this.X.removeAttribute("aria-hidden"),this.player.ud()?g.he(this.X,"ytp-ce-hide-button-lower"):g.cD(this.X,"ytp-ce-hide-button-lower"));else{h=h.getId().substring(15);var W=this.W[h],c=this.N[h];g.he(W.element,"ytp-ce-element-show");W.element.removeAttribute("aria-hidden");
W=this.player.getRootNode();g.he(W,"ytp-ce-shown");I6(this,c.impressionUrls);(W=g.q_())&&g.YN(W,c.visualElement);this.player.B().Z&&this.player.Iz("endscreenelementshown",h)}};
g.l.onCueRangeExit=function(h){if(h.getId()==="ytp-ce-in-endscreen")this.X&&(g.cD(this.X,"ytp-ce-element-show"),this.X.setAttribute("aria-hidden","true"));else{h=h.getId().substring(15);var W=this.W[h];g.cD(W.element,"ytp-ce-element-show");W.element.setAttribute("aria-hidden","true");W=this.player.getRootNode();g.cD(W,"ytp-ce-shown");this.player.B().Z&&this.player.Iz("endscreenelementhidden",h)}};
g.l.m$W=function(h){var W=this;h.target===window&&(new g.oD(function(){for(var c=g.e(Object.values(W.W)),V=c.next();!V.done;V=c.next())g.V$(V.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.l.pJ=function(h){for(var W=g.e(Object.values(this.W)),c=W.next();!c.done;c=W.next())c=c.value,h?c.element.setAttribute("hidden",""):c.element.removeAttribute("hidden")};
g.l.tzM=function(h){this.X&&this.player.getRootNode().removeChild(this.X);h&&(g.he(h,"ytp-ce-hide-button-container"),this.X=h,g.ge(this.player,this.X,4))};
var Ti6=[346,426,470,506,570,640,853,1280,1920],NiU="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),tpt=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Xot=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var MFK={GrH:"current",c2O:"new"};var yIX={CLOSE:"close",pvn:"openUrl",SUBSCRIBE:"subscribe"},PAc={Ick:"click",CLOSE:"close",dqM:"hidden",Uon:"rollOut",oeM:"rollOver",BKz:"shown"};bZI.prototype.Ly=function(){var h=T_f(this,function(W){return W.type==="openUrl"&&W.url!=null});
return h?h.url:null};
var PrS={eVO:"anchored",nS:"branding",CHANNEL:"channel",arB:"cta",vON:"highlightText",AaN:"label",PLAYLIST:"playlist",POPUP:"popup",u6W:"speech",SUBSCRIBE:"subscribe",b9N:"title",VIDEO:"video",Vfk:"website"},yq2={nS:"branding",FvB:"card",LRN:"drawer",Pdk:"highlight",kSg:"marker",zuB:"promotion",TEXT:"text",SUz:"widget"};g.n(ko,g.N);g.l=ko.prototype;g.l.addCueRange=function(h,W,c,V,H){h=new g.t$(h,W,{id:c,namespace:"annotations_module"});V&&this.yg.set(h,V);H&&this.Jk.set(h,H);this.context.L.Fi([h],1)};
g.l.BF=function(){this.context.W.subscribe("resize",this.J8,this)};
g.l.fJ=function(){return this.element};
g.l.oW=function(h,W,c,V,H,B){if(this.Ef)return!1;B&&(B.stopPropagation(),B.preventDefault());this.navigate(h,c,V,H);return!1};
g.l.show=function(){};
g.l.hide=function(){};
g.l.destroy=function(){g.nk(this.fJ())};
g.l.J8=function(){};
g.l.navigate=function(h,W,c,V){var H=this,B=Oy(h);if(B){var E=pXX(B,h.target),J=function(){h.X&&H.context.L.pauseVideo();var u=H.context.videoData.B0||!1,d=g.wO(B||"");u&&d&&(d.v||d.list)?H.context.L.Av(d.v,W,d.list,!1):g.T3(B||"",E==="current"?"_top":void 0,W)};
E==="new"&&(J(),J=null);uP(this.context.logger,c,J,V);o3t(B)||(c=g.q_(),V=W.itct,c&&V&&g.DT(c,g.GE(V)))}};
g.l.dE=function(){this.yg.clear();this.Jk.clear();g.N.prototype.dE.call(this)};
g.l.createElement=function(h){h=new g.p(h);g.X(this,h);return h.element};g.n(YpI,ko);g.l=YpI.prototype;g.l.n$=function(){this.Wk&&s8(this,this.Wk)};
g.l.isAvailable=function(){var h;if(h=!!this.cards.length)(h=this.L.getRootNode())?(h=g.WW(h),h=173<h.width&&173<h.height):h=!1;return h};
g.l.J8=function(){var h=this.isAvailable();g.cW(this.fJ(),h);g.$y(this.context.L.getRootNode(),g.ly.IV_DRAWER_ENABLED,h);My(this.L)};
g.l.destroy=function(){this.L.uo(!1);try{this.L.getRootNode().removeChild(this.Y)}catch(h){}g.gI(this.XI);g.zR(this.CM);this.Rz&&this.Rz.dispose();this.N&&this.N.dispose();ko.prototype.destroy.call(this)};
g.l.NI=function(){var h=this;this.context.X.listen(g.EH("iv-drawer-close-button",this.Y),"click",this.Qq,this);this.context.X.listen(this.W,"touchend",function(){h.DH.start()});
this.context.X.listen(this.W,"scroll",this.TE,this);this.context.W.subscribe("onHideControls",function(){h.Nn=!0});
this.context.W.subscribe("onShowControls",function(){h.Nn=!1});
this.context.W.subscribe("onVideoAreaChange",function(){h.Nn=g.k$(h.L.getRootNode(),"ytp-autohide")});
this.XI.push(g.S5("iv-button-shown",this.eh,this));this.XI.push(g.S5("iv-button-hidden",this.B$,this));hr6(this)};
g.l.findLastIndex=function(h){if(this.cards.length===0)return 0;var W=g.af(this.cards,function(c){return h.g3.startMs>c.g3.startMs||h.g3.startMs===c.g3.startMs&&h.g3.timestamp>=c.g3.timestamp?!0:!1});
return W===-1?0:W+1};
g.l.Qq=function(){if(this.G){uP(this.context.logger,E8(this).Gr.close);var h=g.q_();h&&this.Z&&g.DT(h,this.Z);VZ(this)}};
g.l.TE=function(){g.$y(this.Y,"iv-drawer-scrolled",this.W.scrollTop>0)};
g.l.eh=function(){var h=g.q_(),W=E8(this);W=W?W.c9:this.c9;h&&W&&g.O9(h,[W])};
g.l.B$=function(){var h=g.q_(),W=E8(this);W=W?W.c9:this.c9;h&&W&&g.S2(h,[W])};
g.l.pS=function(){var h=E8(this);uP(this.context.logger,h.Gr.TC);var W=g.q_();if(W&&h)if(this.L.j("web_infocards_teaser_show_logging_fix")){var c=[];h.xC&&c.push(h.xC);h.c9&&c.push(h.c9);c.length>0&&g.O9(W,c)}else g.O9(W,[h.xC,h.c9])};
g.l.E1=function(){var h=g.q_(),W=E8(this);h&&W&&g.S2(h,[W.xC])};
g.l.tS=function(h){var W=E8(this),c=g.q_();this.X?h?(h=this.context.logger,uP(h,W.Gr.GU),h.L.sendVideoStatsEngageEvent(4,void 0),c&&W.xC&&g.DT(c,W.xC)):(h=this.context.logger,uP(h,W.Gr.GU),h.L.sendVideoStatsEngageEvent(4,void 0),c&&W.c9&&g.DT(c,W.c9)):(h=this.context.logger,uP(h,W.Gr.GU),h.L.sendVideoStatsEngageEvent(4,void 0),c&&this.c9&&g.DT(c,this.c9))};g.n(Rz,ko);Rz.prototype.BF=function(){ko.prototype.BF.call(this);BiX(this)};
Rz.prototype.show=function(){ko.prototype.show.call(this);var h=g.q_(),W=this.annotation.data;h&&W&&(W=W.session_data)&&g.O9(h,[g.GE(W.itct)])};
Rz.prototype.hide=function(){ko.prototype.hide.call(this);var h=g.q_(),W=this.annotation.data;h&&W&&(W=W.session_data)&&g.S2(h,[g.GE(W.itct)])};g.n(Jy,Rz);
Jy.prototype.show=function(){if(!this.isActive){Rz.prototype.show.call(this);if(!this.S){g.he(this.fJ(),"iv-branding");var h=this.annotation.data;this.W=this.createElement({D:"img",LM:["branding-img","iv-click-target"],J:{"aria-label":"Channel watermark",src:h.image_url,width:h.image_width,height:h.image_height}});g.cW(this.W,!1);var W=this.createElement({D:"button",LM:["branding-img-container","ytp-button"]});W.appendChild(this.W);this.fJ().appendChild(W);var c=this.annotation.Ly();c&&hy(this,W,
c,this.annotation.id,h.session_data);this.context.L.j("disable_branding_context")||uM2(this,h);this.S=!0}g.cW(this.fJ(),!0);this.isActive=!0;if(this.W){try{EL6(this,this.W)}catch(V){}g.he(this.context.L.getRootNode(),"ytp-branding-shown");this.context.L.getRootNode().style.setProperty("--branding-image-width",this.W.getAttribute("width")+"px")}}};
Jy.prototype.hide=function(){this.isActive&&(Rz.prototype.hide.call(this),g.cW(this.fJ(),!1),this.isActive=!1,g.cD(this.context.L.getRootNode(),"ytp-branding-shown"))};
Jy.prototype.destroy=function(){this.X&&(this.X.dispose(),this.X=null);g.cD(this.context.L.getRootNode(),"ytp-branding-shown");Rz.prototype.destroy.call(this)};g.n(G0U,Rz);g.l=G0U.prototype;g.l.show=function(){this.isActive||(Rz.prototype.show.call(this),this.T||(rq2(this),this.T=!0),g.cW(this.fJ(),!0),g.PK(function(){g.cD(this.fJ(),"iv-promo-inactive")},100,this),this.fJ().removeAttribute("aria-hidden"),this.isActive=!0,nLS(this),qWl(this),x3t(this,this.N))};
g.l.hide=function(){this.isActive&&(g.he(this.fJ(),"iv-promo-inactive"),this.isActive=!1,this.fJ().setAttribute("aria-hidden","true"))};
g.l.oW=function(h,W,c,V,H,B){return this.isCollapsed?!1:Rz.prototype.oW.call(this,h,W,c,V,H,B)};
g.l.oY=function(h){this.Z=!0;Z7l(this,500,h)};
g.l.Uo=function(){this.Z=!1;l4U(this)};
g.l.SY=function(h){h.stopPropagation();this.hide()};
g.l.RY=function(h){h.stopPropagation();nLS(this);this.isCollapsed=!0;g.he(this.fJ(),"iv-promo-collapsed-no-delay");this.C.start()};
g.l.destroy=function(){this.C.dispose();Rz.prototype.destroy.call(this)};g.n(a4U,g.K3);g.l=a4U.prototype;g.l.Et=function(h,W){if(!b7u(this.player.B().playerStyle))return null;switch(h){case "loadCustomAnnotationsXml":return(h=g.WC(W))&&i7f(this,h),!0;case "removeCustomAnnotationById":return W&&this.X&&(DT6(this.X,W),My(this.player)),!0}return null};
g.l.getOptions=function(){return b7u(this.player.B().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.l.Sb=function(){var h=this.player.B(),W=this.player.getVideoData(),c=h.annotationsLoadPolicy||W.annotationsLoadPolicy;return W.B0||this.player.isMutedByEmbedsMutedAutoplay()?!1:c===1&&!W.lq||h.Nn.get(W.videoId)||g.h7(W)||g.WN(W)?!0:!1};
g.l.oA=function(){if(this.G){var h=this.player.Bk().getVideoContentRect(!0);g.h3(this.G.element,h.width,h.height);g.gb(this.G.element,h.left,h.top)}if(this.X){var W=this.player.Hv();h=this.X;W=W.width;g.$y(h.Y,"iv-drawer-small",W<=426);g.$y(h.Y,"iv-drawer-big",W>=1280)}};
g.l.Bg=function(h){zr6(this,h.state);g.Y(h.state,2)&&(this.ud()&&this.Q7()&&this.player.getPresentingPlayerType()!==2&&this.XL(!1),this.uo(!1))};
g.l.load=function(){function h(E){var J=W.loadNumber;W.C=null;W.loaded&&W.loadNumber===J&&W.player.getVideoData().videoId===V&&(E=g.EB(E)&&E.responseXML?E.responseXML:null)&&(i7f(W,E),g.he(W.player.getRootNode(),"iv-module-loaded"))}
var W=this;g.K3.prototype.load.call(this);zr6(this,this.player.getPlayerStateObject());this.loadNumber++;var c=this.player.getVideoData(),V=c.videoId;g.St()&&(h=KuU(this,h));var H={format:"XML",onFinish:h,onError:function(){W.C=null},
urlParams:{}};c.isPharma&&(H.urlParams.pharma="1");H.method="POST";H.withCredentials=!0;var B=this.player.B().Nn.get(V);B&&Aq2(H,B);B=B&&(B.l5||B.Bz);if(!c.eb||B)c.CM?QV6(this,c.CM,H):(this.S=function(){if(!W.Z)W.onVideoDataChange(H);var E=W.player.getVideoData();(E==null?0:g.kq(E))&&!W.XI&&Fuc(W,E)},this.player.addEventListener("videodatachange",this.S));
g.ge(this.player,this.G.element,4);this.oA();(B=g.h7(c))&&Mpf(this,B);(B=g.WN(c))&&B.featuredChannel&&f46(this,B.featuredChannel,B.annotationId||"branding",c.videoId||null,c.eventId||null);this.iJ=g.EH("ytp-cards-button",this.player.getRootNode());g.kq(c)&&Fuc(this,c)};
g.l.onVideoDataChange=function(h){var W=this.player.getVideoData();W.CM&&QV6(this,W.CM,h)};
g.l.unload=function(){this.player.zw("annotations_module");for(var h=g.e(Object.keys(this.N)),W=h.next();!W.done;W=h.next())this.N[W.value].destroy();this.T=null;this.X&&(this.X.destroy(),this.X=null,My(this.player));this.Z=!1;this.C&&(this.C.abort(),this.C=null);this.XI=!1;this.N={};this.W.hide();g.K3.prototype.unload.call(this);this.G.detach();this.S&&(this.player.removeEventListener("videodatachange",this.S),this.S=null)};
g.l.G9=function(h){h===this.player.getVideoData().videoId&&(this.loaded?U3$(this):this.load())};
g.l.ud=function(){var h;return((h=this.X)==null?void 0:h.isAvailable())||this.XI};
g.l.Q7=function(){return!!this.X&&this.X.G};
g.l.XL=function(h,W,c){W=W===void 0?!1:W;this.ud();this.X&&(h?c?cj(this.X,c,W):cj(this.X,"YOUTUBE_DRAWER_AUTO_OPEN",W):VZ(this.X))};
g.l.uo=function(h,W){this.player.publish(h?"cardsteasershow":"cardsteaserhide",W)};
g.l.dE=function(){this.player.B().Nn.unsubscribe("vast_info_card_add",this.G9,this);g.cD(this.player.getRootNode(),g.ly.IV_DRAWER_OPEN);for(var h=this.Wk,W=g.Py,c=0,V=h.length;c<V;c++)W.XV(h[c]);this.Wk.length=0;g.K3.prototype.dE.call(this)};
g.l.createElement=function(h){h=new g.p(h);g.X(this,h);return h.element};g.i3("annotations_module",a4U);g.i3("creatorendscreen",qpf);})(_yt_player);
